version: '3'
services:
    typingtarzan:
        build: 
            context: ./main
        ports:
            - 8080:${HTTP_PORT} #http server
            - ${WEBSOCKET_PORT}:${WEBSOCKET_PORT} #web socket server
        links:
            - 'mariadb'

        # sync development files from host to vm
        volumes:
            - "./main/typingtarzan/src:/typingtarzan/src"
            - "./main/typingtarzan/webroot:/typingtarzan/webroot"
        environment:
            SERVER_HOSTNAME: "localhost"
            HTTP_PORT: ${HTTP_PORT}
            WEBSOCKET_PORT: ${WEBSOCKET_PORT}
        env_file:
            - ./db/env # include sql credentials

    mariadb:
        build:
            context: ./db
        volumes:
            - ./db/ttar.sql:/docker-entrypoint-initdb.d/dump.sql
            - mariadb:/var/lib/mysql
        env_file:
            - ./db/env
        healthcheck:
            test: ["CMD-SHELL", 'mysql -u=$$MYSQL_USER --database=$$MYSQL_DATABASE --password=$$MYSQL_PASSWORD']
            interval: 30s
            timeout: 10s
            retries: 5

volumes:
    mariadb:
