version: '3'
services:
    typingtarzan:
        build: 
            context: ./main
        ports:
            - 8080:8080 #http server
            - 8081:8081 #web socket server
        links:
            - 'mariadb'

        # sync development files from host to vm
        volumes:
            - "./main/typingtarzan/src:/typingtarzan/src"
            - "./main/typingtarzan/webroot:/typingtarzan/webroot"

    mariadb:
        build:
            context: ./db
        ports:
            - 3306:3306
        volumes:
            - ./db/ttar.sql:/docker-entrypoint-initdb.d/dump.sql
            - mariadb:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_DATABASE: 'ttar'
        healthcheck:
            test: ["CMD-SHELL", 'mysql --database=$$MYSQL_DATABASE --password=$$MYSQL_ROOT_PASSWORD']
            interval: 30s
            timeout: 10s
            retries: 5

volumes:
    mariadb:
